---

- name: R1 setting
  hosts: R1
  gather_facts: no

  tasks:
    - name: R1 int ip address
      cisco.ios.ios_l3_interfaces:
        config:
          - name: GigabitEthernet0/1
            ipv4:
              - address: 192.168.1.1/24
        state: merged

    - name: GigabitEthernet0/0 no shutdown
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet0/1
            enabled: yes
        state: merged
    
    - name: R1 Vlan
      cisco.ios.ios_vlans:
        config:
          - name: Vlan_10
            vlan_id: 10
            state: active
            shutdown: disabled

    - name: ios facts
      cisco.ios.ios_facts:
        gather_subset: all
        gather_network_resources: interfaces
      register: result

    - name: ios facts debug
      debug:
        msg: "{{result}}"

#   handlers:
#     - name:

# - name: switch1 setting
# hosts: switch1
# gather_facts: yes

# tasks:
#   - name: 

# handlers:
#   - name: