---

- name: R1 setting
  hosts: R1
  gather_facts: no

  vars:
    trank1_vlan_int: FastEthernet1/0/23
    trank2_vlan_int: FastEthernet1/0/24

  tasks:
    - name: vlan10 setting
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.10.1 255.255.255.0
          - glbp 10 ip 192.168.10.254
          - glbp 10 priority 105
          - glbp 10 preempt
        parents: interface vlan10

    - name: vlan20 setting
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.20.1 255.255.255.0
          - glbp 20 ip 192.168.20.254
          - glbp 20 priority 105
          - glbp 20 preempt
        parents: interface vlan20
    
    - name: vlan30 setting
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.30.1 255.255.255.0
          - glbp 30 ip 192.168.30.254
          - glbp 30 priority 105
          - glbp 30 preempt
        parents: interface vlan30
    
    - name: R1 setting
      cisco.ios.ios_config:
        lines:
          - interface range fa1/0/23-24
          - switchport trunk encapsulation dot1q
          - switchport mode trunk 

    - name: ios facts
      cisco.ios.ios_facts:
        gather_subset: all
        gather_network_resources: interfaces
      register: result

    - name: ios facts debug
      debug:
        msg: "{{result}}"
