---

- name: R2 setting
  hosts: R2
  gather_facts: no

  tasks:
    - name: vlan10 setting
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.10.2 255.255.255.0
          - glbp 10 ip 192.168.10.254
          - glbp 10 preempt
        parents: interface vlan10

    - name: vlan20 setting
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.20.2 255.255.255.0
          - glbp 20 ip 192.168.20.254
          - glbp 20 preempt
        parents: interface vlan20
    
    - name: vlan30 setting
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.30.2 255.255.255.0
          - glbp 30 ip 192.168.30.254
          - glbp 30 preempt
        parents: interface vlan30

    - name: R2 setting
      cisco.ios.ios_config:
        lines:
          - interface range fa1/0/23-24
          - switchport trunk encapsulation dot1q
          - switchport mode trunk 
