---

- name: S1 setting
  hosts: S1
  gather_facts: no

  vars: #インターフェイス名
    vlan10_int:  #例 FastEthernet0/1
    vlan20_int:
    trank_vlan_int:

  tasks:
    - name: setting vlan10
      cisco.ios.ios_vlans:
        config:
          - name: Vlan_10
            vlan_id: 10
            state: active
            shutdown: disabled
        state: merged

    - name: setting vlan20
      cisco.ios.ios_vlans:
        config:
          - name: Vlan_20
            vlan_id: 20
            state: active
            shutdown: disabled
        state: merged

    - name: S1 vlan setteing
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ vlan10_int }}"
            mode: access
            access:
              vlan: 10
          - name: "{{ vlan20_int }}"
            mode: access
            access:
              vlan: 20
          - name: "{{ trank_vlan_int }}"
            mode: trunk
            trunk:
              native_vlan: 1
        state: merged

    - name: ios facts
        cisco.ios.ios_facts:
          gather_subset: all
          gather_network_resources: interfaces
        register: result

    - name: ios facts debug
      debug:
        msg: "{{result}}"
