---

- name: S1の設定
  hosts: S1
  gather_facts: no

  vars: #インターフェイス名
    vlan10_int1: FastEthernet0/1 #例 FastEthernet0/1
    vlan10_int2: FastEthernet0/2
    trank1_vlan_int: FastEthernet0/23
    trank2_vlan_int: FastEthernet0/24


  tasks:
    - name: vlan10の作成
      cisco.ios.ios_vlans:
        config:
          - name: Vlan10
            vlan_id: 10
            state: active
            shutdown: disabled
        state: merged
        
    - name: S1のvlan設定
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ vlan10_int1 }}"
            mode: access
            access:
              vlan: 10
          - name: "{{ vlan10_int2 }}"
            mode: access
            access:
              vlan: 10
          - name: "{{ trank1_vlan_int }}"
            mode: trunk
            trunk:
              native_vlan: 1
          - name: "{{ trank2_vlan_int }}"
            mode: trunk
            trunk:
              native_vlan: 1
        state: merged
        
    - name: S1の情報取得
      cisco.ios.ios_facts:
        gather_subset: all
        gather_network_resources: interfaces
      register: result
      
    - name: 取得した情報の表示
      debug:
        msg: "{{result}}"
