---

- name: S2 setting
  hosts: S2
  gather_facts: no

  vars: #インターフェイス名
    vlan20_int: FastEthernet0/1 #例 FastEthernet0/1
    vlan30_int: FastEthernet0/2
    trank1_vlan_int: FastEthernet0/23
    trank2_vlan_int: FastEthernet0/24

  tasks:
    - name: setting vlan20
      cisco.ios.ios_vlans:
        config:
          - name: Vlan_20
            vlan_id: 20
            state: active
            shutdown: disabled
        state: merged

    - name: setting vlan30
      cisco.ios.ios_vlans:
        config:
          - name: Vlan_30
            vlan_id: 30
            state: active
            shutdown: disabled
        state: merged

    - name: S2 vlan setteing
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ vlan20_int }}"
            mode: access
            access:
              vlan: 20
          - name: "{{ vlan30_int }}"
            mode: access
            access:
              vlan: 30
          - name: "{{ trank1_vlan_int }}"
            mode: trunk
            trunk:
              native_vlan: 1
          - name: "{{ trank2_vlan_int }}"
            mode: trunk
            trunk:
              native_vlan: 1
        state: merged

    - name: ios facts
      cisco.ios.ios_facts:
        gather_subset: all
        gather_network_resources: interfaces
      register: result

    - name: ios facts debug
      debug:
        msg: "{{result}}"
