---

- name: S2の設定
  hosts: S2
  gather_facts: no

  vars: #インターフェイス名
    vlan20_int: FastEthernet0/1 #例 FastEthernet0/1
    vlan30_int: FastEthernet0/2
    trank1_vlan_int: FastEthernet0/23
    trank2_vlan_int: FastEthernet0/24

  tasks:
    - name: vlan20の作成
      cisco.ios.ios_vlans:
        config:
          - name: Vlan20
            vlan_id: 20
            state: active
            shutdown: disabled
        state: merged

    - name: vlan30の作成
      cisco.ios.ios_vlans:
        config:
          - name: Vlan30
            vlan_id: 30
            state: active
            shutdown: disabled
        state: merged

    - name: S2のvlan設定
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ vlan20_int }}"
            mode: access
            access:
              vlan: 20
          - name: "{{ vlan30_int }}"
            mode: access
            access:
              vlan: 30
          - name: "{{ trank1_vlan_int }}"
            mode: trunk
            trunk:
              native_vlan: 1
          - name: "{{ trank2_vlan_int }}"
            mode: trunk
            trunk:
              native_vlan: 1
        state: merged

    - name: S2の情報取得
      cisco.ios.ios_facts:
        gather_subset: all
        gather_network_resources: interfaces
      register: result

    - name: 取得した情報の表示
      debug:
        msg: "{{result}}"
