---

- name: S1 setting
  hosts: S1
  gather_facts: no

  tasks:

    - name: setting vlan
      cisco.ios.ios_vlans:
        config:
          - name: Vlan_10
            vlan_id: 10
            state: active
            shutdown: disabled
        state: merged

    - name: S1 vlan setteing
      cisco.ios.ios_l2_interfaces:
        config:
          - name: FastEthernet0/5
            mode: access
            access:
              vlan: 10
          - name: FastEthernet0/6
            mode: access
            access:
              vlan: 10
          - name: FastEthernet0/1
            mode: trunk
            trunk:
              native_vlan: 1
              # encapsulation: dot1q
        state: merged

    - name: ios facts
      cisco.ios.ios_facts:
        gather_subset: all
        gather_network_resources: interfaces
      register: result

    - name: ios facts debug
      debug:
        msg: "{{result}}"

#   handlers:
#     - name:
